language: java
dist: trusty
jdk:
  - oraclejdk8
  - oraclejdk9
script:
  - ./gradlew compileJava_minJosm
  - ./gradlew compileJava_latestJosm
  - ./gradlew build

deploy:
  provider: releases
  file_glob: true
  api_key: "${GH_TOKEN}"
  file:
    - "build/dist/matsim.jar"
    - "build/tmp/jar/MANIFEST.MF"
  skip_cleanup: true
  on:
    condition: -n $GH_TOKEN
    tags: true
    jdk: oraclejdk8
